- .gitignore
- .tool-versions
- Makefile
- scripts/docker/docker.lib.sh
- scripts/docker/dockerfile-linter.sh
- scripts/githooks/check-english-usage.sh
- scripts/githooks/check-file-format.sh
- scripts/githooks/check-markdown-format.sh
- scripts/githooks/check-terraform-format.sh
- scripts/githooks/scan-secrets.sh
- scripts/reports/create-sbom-report.sh
- scripts/reports/scan-vulnerabilities.sh
- scripts/shellscript-linter.sh
- scripts/terraform/terraform.sh
> FDOS_129 Enable use of podman or docker

- infrastructure/common/common-variables.tf
- infrastructure/common/locals.tf
- infrastructure/common/provider.tf
- infrastructure/common/versions.tf
- infrastructure/local/versions.tf
- infrastructure/remote/versions.tf
- infrastructure/stacks/account_wide/README.md
- infrastructure/stacks/account_wide/iam.tf
- infrastructure/stacks/account_wide/variables.tf
- infrastructure/stacks/terraform_management/dynamodb.tf
- infrastructure/stacks/terraform_management/s3.tf
- infrastructure/stacks/terraform_management/variables.tf
- scripts/workflow/bootstrapper.sh
> FDOS-142 Bootstrap repo dev

- .github/workflows/pipeline-deploy-account-infrastructure.yaml
- infrastructure/.gitignore
- infrastructure/account_wide.tfvars
- infrastructure/common.tfvars
- infrastructure/common/common-variables.tf
- infrastructure/common/provider.tf
- infrastructure/environments/dev.tfvars
- infrastructure/project.tfvars
- infrastructure/stacks/account_wide/README.md
- infrastructure/stacks/account_wide/variables.tf
- infrastructure/stacks/account_wide/vpc.tf
- infrastructure/terraform_management.tfvars
This PR creates the account wide VPC infrastructure whilst updating the account level development workflow, tidying up tags & introducing variables. 
---
> FDOS-156 Create account wide VPC infrastructure

- infrastructure/account_wide.tfvars
- infrastructure/environments/dev.tfvars
- infrastructure/stacks/account_wide/variables.tf
Move VPC variables to accommodate multiple environments in the future and add database route table.
---
> FDOS-156 Move vpc vars to accommodate multiple env and add database route table

- README.md
- scripts/config/pre-commit.yaml
- scripts/config/vale/styles/config/vocabularies/words/accept.txt
- scripts/githooks/check-branch-name.sh
- scripts/githooks/check-commit-message.sh
- scripts/githooks/commit-msg
- scripts/init.mk
> FDOS-160 Branch name commit message rules

- infrastructure/common.tfvars
- infrastructure/common/common-variables.tf
- infrastructure/data_migration.tfvars
- infrastructure/modules/s3/main.tf
- infrastructure/modules/s3/variables.tf
- infrastructure/project.tfvars
- infrastructure/stacks/data_migration/s3.tf
- infrastructure/stacks/data_migration/variables.tf
- scripts/workflow/action-infra-stack.sh
- scripts/workflow/bootstrapper.sh
> FDOS-167 Add bucket for data migration

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- scripts/githooks/check-branch-name.sh
- scripts/githooks/check-commit-message.sh
Update readme to remove place holder code from template repo
Also enable branch name and commit message checks to handle lower case Jira references
---
> FDOS-166 update placeholder readme

- .github/workflows/fdos-pipeline-infrastructure-cleardown.yaml
> FDOS-201 Handle environment as array in cleardown

- .github/workflows/pipeline-deploy-is-application.yaml
- infrastructure/gp_search.tfvars
- infrastructure/stacks/gp_search/s3.tf
- infrastructure/stacks/gp_search/variables.tf
Change to have a working pipeline for a new Integrated Search stack, with a working pipeline with security secrets scans, that will stand up infrastructure in the Dev account, in this instance a basic S3 bucket for the GP_Search POC.
Also additional fix to derive workspace script to allow branch names with -'s
The aims of the pipline are:
- Fire upon a push to a branch with the IS naming convention (i.e. task/DOSIS*) and ensure successful deployment to development environment 
- Run the scan-secrets action check to for secrets (just need to test to make sure this stage is run) 
- Deploy an S3 bucket to the development environment from IS service infrastructure stack inside infrastructure/stacks/gp_search
This is to start the POC work and build the basis for the POC to be built. By adding …
> DOSIS-355 Setting up IS POC Pipeline and s3

- .github/workflows/deploy-architecture-pages.yaml
> Fix syntax error in github action file

- .github/workflows/build-service.yaml
- .github/workflows/deploy-infrastructure.yaml
- scripts/githooks/check-file-format.sh
> FDOS-244 Handle stacks with no artefact

- .github/actions/action-infrastructure-stack/action.yaml
- .github/workflows/build-service.yaml
- .github/workflows/deploy-infrastructure.yaml
- .github/workflows/pipeline-deploy-fdos-application.yaml
- infrastructure/common.tfvars
- infrastructure/common/common-variables.tf
- infrastructure/common/locals.tf
- infrastructure/common/provider.tf
- infrastructure/data_migration.tfvars
- infrastructure/modules/dynamodb/locals.tf
- infrastructure/modules/dynamodb/main.tf
- infrastructure/modules/lambda/locals.tf
- infrastructure/modules/lambda/main.tf
- infrastructure/modules/lambda/variables.tf
- infrastructure/modules/s3/locals.tf
- infrastructure/modules/s3/main.tf
- infrastructure/stacks/account_wide/s3.tf
- infrastructure/stacks/data_migration/data.tf
- infrastructure/stacks/data_migration/lambda.tf
- infrastructure/stacks/data_migration/security_group.tf
- infrastructure/stacks/data_migration/variables.tf
- scripts/workflow/action-infra-stack.sh
- services/data-migration/Makefile
- services/data-migration/README.md
This PR introduces the deployment of the Extract Lambda function as part of the data-migration service. It includes infrastructure updates to provision the necessary AWS resources, enhancements to CI/CD workflows, and improvements to the packaging and publishing process.
Key Changes:
- Added Terraform configurations to provision the Extract Lambda function.
- Defined IAM policies, security groups, and S3 artifact storage.
- Updated GitHub Actions workflows to support Lambda deployment.
- Add feature workspaces for feature branches whilst keeping main as environment workspace.
- Implemented S3 artifact publishing for the Python dependency layer in the Makefile due to its size being too large for local storage.
- Updated README.md with instructions on building the Lambda function.
- Set the …
> FDOS-184 Package deploy extract lambda

- .github/workflows/deploy-infrastructure.yaml
Change commit hash to be optional for the infrastructure plan & apply. 
---
> FDOS-184 Change commit hash to be optional

- .github/workflows/fdos-pipeline-infrastructure-cleardown.yaml
- infrastructure/common/locals.tf
- infrastructure/common/provider.tf
- infrastructure/modules/dynamodb/locals.tf
- infrastructure/modules/dynamodb/main.tf
- infrastructure/modules/lambda/locals.tf
- infrastructure/modules/lambda/main.tf
- infrastructure/modules/s3/locals.tf
- infrastructure/modules/s3/main.tf
- infrastructure/stacks/data_migration/lambda.tf
- infrastructure/stacks/data_migration/security_group.tf
Revert workspace variable to old format & pass variables to clear down artefacts.
---
> FDOS-184 Revert workspace variable to old format

- .github/actions/artefact-cleardown/action.yaml
- .github/workflows/artefacts-cleardown.yaml
- .github/workflows/fdos-pipeline-infrastructure-cleardown.yaml
- .github/workflows/infrastructure-cleardown.yaml
- infrastructure/data_migration.tfvars
- infrastructure/stacks/data_migration/lambda.tf
- infrastructure/stacks/data_migration/security_group.tf
- infrastructure/stacks/data_migration/variables.tf
- scripts/workflow/cleardown-artefacts.sh
- services/data-migration/poetry.lock
- services/data-migration/pyproject.toml
Create transform Lambda using Pandas Lambda layer instead of packing dependencies, while amending FDOS cleardown workflow.
---
> FDOS-188 Package and deploy transform lambda

- services/data-migration/README.md
> FDOS-000 Add detail based on use of readme

- .github/workflows/pipeline-deploy-fdos-application.yaml
- infrastructure/database.tfvars
- infrastructure/modules/dynamodb/main.tf
- infrastructure/modules/dynamodb/variables.tf
- infrastructure/stacks/database/dynamodb.tf
- infrastructure/stacks/database/variables.tf
This PR creates a database stack with dynamodb.
---
> FDOS-267 Create database stack

- infrastructure/stacks/database/dynamodb.tf
> FDOS-267 Remove double workspace reference

- .github/workflows/fdos-pipeline-infrastructure-cleardown.yaml
- infrastructure/github_runner.tfvars
- scripts/workflow/action-infra-stack.sh
Amend FDOS cleardown to delete artefacts in the mgmt bucket whilst dynamically select an existing Terraform workspace or create a new one if it doesn't exist, improving workspace management automation.
---
> FDOS-204 amend fdos cleardown workflow

- infrastructure/README.md
- infrastructure/common.tfvars
- infrastructure/common/common-variables.tf
- infrastructure/common/locals.tf
- infrastructure/common/provider.tf
- infrastructure/data_migration.tfvars
- infrastructure/database.tfvars
- infrastructure/stacks/account_wide/data.tf
- infrastructure/stacks/account_wide/variables.tf
- infrastructure/stacks/account_wide/vpc.tf
- infrastructure/stacks/account_wide/vpn.tf
- infrastructure/stacks/data_migration/data.tf
- infrastructure/stacks/data_migration/lambda.tf
- infrastructure/stacks/data_migration/rds.tf
- infrastructure/stacks/data_migration/s3.tf
- infrastructure/stacks/data_migration/security_group.tf
- infrastructure/stacks/data_migration/variables.tf
- infrastructure/stacks/database/dynamodb.tf
- infrastructure/stacks/github_runner/iam.tf
- scripts/config/vale/styles/config/vocabularies/words/accept.txt
- scripts/workflow/action-infra-stack.sh
> FDOS-260 Implement resource naming convention

- infrastructure/stacks/data_migration/data.tf
- infrastructure/stacks/data_migration/lambda.tf
> FDOS-260 Correct path to layer

- .github/workflows/deploy-architecture-pages.yaml
- .github/workflows/pipeline-deploy-fdos-application.yaml
- .github/workflows/pipeline-status-check.yaml
- .github/workflows/slack-notifications.yaml
> FDOS-314 Apply dependabot changes

- application/packages/python/ftrs_data_layer/models.py
- application/packages/python/ftrs_data_layer/tests/test_models.py
- services/data-migration/pipeline/load.py
- services/data-migration/pipeline/transform.py
- services/data-migration/pipeline/utils/dos_db.py
- services/data-migration/tests/unit/test_extract.py
- services/data-migration/tests/unit/test_load.py
- services/data-migration/tests/unit/test_transform.py
- services/data-migration/tests/unit/utils/test_dos_db.py
- services/data-migration/tests/util/stub_data.py
Introduce the location details at noted in #fdos-176 and added linkage to healthcareservice for #fdos-194.
Location (all new data):
```
{
"positionGCS": {
"M": {"latitude": {"S": "53.3832934"}, "longitude": {"S": "-2.8632184"}}
},
"partOf": {"NULL": true},
"positionReferenceNumber_UPRN": {"NULL": true},
"address": {
"M": {
"postcode": {"S": "L25 3PA"},
"town": {"S": "Liverpool"},
"street": {"S": "1 random road$place$Liverpool$Merseyside"},
}
},
"createdDateTime": {"S": "2025-05-05T08:46:01.547071Z"},
"active": {"BOOL": true},
"managingOrganisation": {"S": "f2253b26-1add-41ed-aed4-e758f6b420cd"},
"positionReferenceNumber_UBRN": {"NULL": true},
"createdBy": {"S": "ROBOT"},
"name": {"NULL": true},
"modifiedBy": {"S": "ROBOT"},
"modifiedDateTime": {"S": "2025-05-05T08:46:01.547071Z"},
"id": …
```
> Task/fdos-176 - Extract location details

- .github/workflows/pipeline-deploy-fdos-application.yaml
- .github/workflows/pipeline-fdos-infrastructure-cleardown.yaml
> FDOS-319 Add lower case jira ref as trigger

- infrastructure/common/locals.tf
- infrastructure/stacks/data_migration/data.tf
- infrastructure/stacks/data_migration/lambda.tf
> FDOS-279 FDOS-189 Amend dynamodb table lookup

- README.md
Added more setup configuration steps to avoid pitfalls
Prevents new users from making simple mistakes.
---
> SIA-569 added more configuration steps to README

- .github/workflows/pipeline-fdos-infrastructure-cleardown.yaml
> FDOS-267 Update github pipelines

- infrastructure/data_migration.tfvars
> FDOS-304 Uplift engine version

- .github/workflows/pipeline-fdos-infrastructure-cleardown.yaml
> FDOS-267 fix cleardown pipelines

- .github/workflows/pipeline-deploy-fdos-application.yaml
- .github/workflows/pipeline-fdos-infrastructure-cleardown.yaml
- infrastructure/modules/dynamodb/main.tf
- infrastructure/modules/dynamodb/variables.tf
- infrastructure/opensearch.tfvars
- infrastructure/stacks/database/dynamodb.tf
- infrastructure/stacks/opensearch/cloudwatch.tf
- infrastructure/stacks/opensearch/data.tf
- infrastructure/stacks/opensearch/iam.tf
- infrastructure/stacks/opensearch/opensearch_collection_policy.tf
- infrastructure/stacks/opensearch/opensearch_pipeline.tf
- infrastructure/stacks/opensearch/opensearch_vpce.tf
- infrastructure/stacks/opensearch/outputs.tf
- infrastructure/stacks/opensearch/pipeline-config.yaml.tmpl
- infrastructure/stacks/opensearch/s3.tf
- infrastructure/stacks/opensearch/security_group.tf
- infrastructure/stacks/opensearch/variables.tf
The following was implemented as part of the PR 
1. Create an OpenSearch Ingestion Service pipeline which is workspaced.
2. Manages the network access policy and data access policy.
3. Add opensearch to the stack for build and clear down
4. Add retries, implement DLQ (using S3)
5. Modified DynamoDB tables to implement PITR and remove streaming by default from the module
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. …
> Task/FDOS 315 OpenSearch Ingestion Service

- infrastructure/stacks/account_policies/iam_policies.tf
> FDOS-304 Add missed policies

- .github/workflows/pipeline-fdos-infrastructure-cleardown.yaml
> FDOS-267 Updating how env is passed in cleardown

- .github/workflows/pipeline-fdos-infrastructure-cleardown.yaml
> FDOS-267 Update cleardown to correctly remove artefacts

- infrastructure/stacks/opensearch/s3.tf
Add force destroy to the S3 bucket
---
> FDOS-344 Adding force destroy to the S3 buckets

- scripts/config/grype.yaml
> FDOS-000 Double grype allowed build age

- application/packages/python/ftrs_data_layer/models.py
- application/packages/python/ftrs_data_layer/tests/test_models.py
- services/data-migration/pipeline/extract.py
- services/data-migration/pipeline/transform.py
- services/data-migration/pipeline/utils/dos_db.py
- services/data-migration/pipeline/utils/opening_times.py
- services/data-migration/tests/unit/test_extract.py
- services/data-migration/tests/unit/utils/test_dos_db.py
- services/data-migration/tests/util/fixtures.py
- services/data-migration/tests/util/stub_data.py
- tests/service_automation/tests/conftest.py
- tests/service_automation/tests/pages/ui_pages/result.py
- tests/service_automation/tests/step_definitions/is_api_steps/test_api_google_search.py
- tests/service_automation/tests/step_definitions/is_infra_steps/test_s3_bucket.py
- tests/service_automation/tests/utilities/common/config.py
The changes of this PR bring in the openingTime details for a healthcare service. This change has been reflected into the data model documentation, and follows form the work done prior to transform this data into the correct format.
There was also a ruff format and ruff check --fix ran over the whole codebase hence we see changes to the 'tests/...' files there is no functional changes there. 
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any …
> Task/fdos-177 - ETL Service opening times

- .github/actions/perform-static-analysis/action.yaml
> FDOS-307 Update branch to be ref name for analysis

- infrastructure/stacks/read_only_viewer/cloudfront.tf
> FDOS-302 Add namespace to origin access control

- infrastructure/stacks/etl_ods/lambda.tf
> FDOS-384 Add ssm and execute api permissions to consumer

- docs/specification/dos-ingestion-api-oas.yaml
formatting changes to the `dos-ingestion-oas.yaml` that were requested
---
> SIA-641 made formatting changes to ingestion api oas

- .github/workflows/pipeline-stop-opensearch-ingestion-pipelines.yaml
- services/README.md
> FDOS-388 readme to restart ingestion pipelines

- infrastructure/domain_name.tfvars
> FDOS-392 Update root domain name

- infrastructure/stacks/domain_name/route53.tf
> FDOS-392 Add environment level hosted zone

- .github/workflows/pipeline-deploy-account-infrastructure.yaml
- .github/workflows/pipeline-deploy-fdos-application.yaml
This pull request optimises the GitHub workflows. The main improvements include:
- Refactored matrix usage for both plan and apply jobs to reduce duplication and improve maintainability.
- Consolidated all service builds into a single matrix job (build-services) for better maintainability.
- Improved naming consistency and readability throughout the workflow.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really …
> FDOS-389 Optimise GitHub workflows

- docs/specification/dos-ingestion-api-oas.yaml
Added missing bullet point for a path description
---
> SIA-641 added full stop

- .github/workflows/pipeline-fdos-infrastructure-cleardown.yaml
- .github/workflows/pipeline-is-infrastructure-cleardown.yaml
> FDOS-364 Amend cleardown to run on the correct branches

- infrastructure/stacks/account_wide/data.tf
- infrastructure/stacks/account_wide/vpn.tf
> Task/FDOS-362 Test env baseline fix

- infrastructure/stacks/opensearch/data.tf
- infrastructure/stacks/opensearch/opensearch_pipeline.tf
- infrastructure/stacks/read_only_viewer/data.tf
Modify the data sources for ssm and osc
---
> FDOS-362 Modify the data sources for ssm and osc

- infrastructure/stacks/account_policies/policies/rw_data.json
- infrastructure/stacks/github_runner/app_github_runner_policy.json.tpl
> FDOS-395 FDOS-343 Add dms permissions to roles

- infrastructure/stacks/github_runner/app_github_runner_policy.json.tpl
> DOSIS-4201 Update app runner to include allow get change policy

- infrastructure/stacks/account_policies/policies/rw_infrastructure_management.json
Service Quota Access to infra role
---
> FDOS-459 Service Quota Access to infra role

- infrastructure/stacks/github_runner/app_github_runner_policy.json.tpl
> SIA-671 SIA-971 Add acm permissions to app runner role

- infrastructure/stacks/github_runner/app_github_runner_policy.json.tpl
> SIA-671 Add acm permissions to app runner role

- docs/fhir/codesystems/CodeSystem-England-EndpointBusinessScenario.json
- docs/fhir/examples/Bundle-ServiceDetailsByOdsCode-Example.json
- docs/fhir/examples/OperationOutcome-InternalServerError-Example.json
- docs/fhir/examples/OperationOutcome-InvalidOdsCode-Example.json
- docs/fhir/structuredefinitions/Extension-England-EndpointBusinessScenario.json
- docs/fhir/structuredefinitions/Extension-England-EndpointCompression.json
- docs/fhir/structuredefinitions/Extension-England-OrganizationEndpointOrder.json
- docs/fhir/valuesets/ValueSet-England-EndpointBusinessScenario.json
After feedback from IOPS, they recommended having it on GitHub.
Add better version control for our spec files
---
> DOSIS-1655 Add initial gp search fhir spec

- infrastructure/modules/lambda/data.tf
- infrastructure/modules/lambda/locals.tf
Lambda execution role modification
---
> Task/FDOS-489 Lambda execution role modification

- infrastructure/stacks/account_policies/policies/ro_management.json
- infrastructure/stacks/account_policies/policies/rw_management.json
Add apigateway perms for domain name access assocs
---
> FDOS-486 Add apigateway perms for domain name access assocs

- infrastructure/stacks/account_wide/kms.tf
KMS resource policy modification
---
> Task/FDOS-489 KMS resource policy modification

- infrastructure/stacks/data_migration/rds.tf
> FDOS-414 Enable rds deletion protection

- .gitleaksignore
- scripts/config/gitleaks.toml
> FDOS-450 Fix gitleaks file

- infrastructure/stacks/github_runner/account_github_runner_policy.json.tpl
> FDOS-336 Allow creation of service linked role for opensearch serverless

- .github/workflows/quality-checks.yaml
Upgrade Trivy action to 0.32.0 from 0.31.0
---
> FDOS-522 Upgrade Trivy action to 0.32.0 from 0.31.0

- docs/fhir/codesystems/CodeSystem-England-EndpointBusinessScenario.json
- docs/fhir/examples/Bundle-ServiceDetailsByOdsCode-Example.json
- docs/fhir/structuredefinitions/Extension-England-EndpointBusinessScenario.json
- docs/fhir/structuredefinitions/Extension-England-EndpointCompression.json
- docs/fhir/structuredefinitions/Extension-England-OrganizationEndpointOrder.json
- docs/fhir/valuesets/ValueSet-England-EndpointBusinessScenario.json
- services/gp-search/functions/ftrs_service/fhir_mapper/endpoint_mapper.py
- services/gp-search/tests/conftest.py
- services/gp-search/tests/unit/functions/ftrs_service/fhir_mapper/test_endpoint_mapper.py
> DOSIS-1600 Use extensions instead of header for endpoint

- infrastructure/crud_apis.tfvars
- infrastructure/stacks/crud_apis/lambda.tf
- infrastructure/stacks/crud_apis/variables.tf
added pandas layer to crud api lambda
---
> SIA-649 added pandas layer to crud lambda

- .github/workflows/pipeline-deploy-application.yaml
- .github/workflows/slack-notifications.yaml
> FDOS-525 Apply dependabot recommended uplift to slack action

- application/packages/python/ftrs_common/tests/utils/test_api_url_util.py
- application/packages/python/ftrs_common/utils/api_url_util.py
- scripts/workflow/service-automation-tests.sh
- tests/service_automation/tests/conftest.py
- tests/service_automation/tests/features/is_infra_features/lambda.feature
- tests/service_automation/tests/utilities/common/resource_name.py
- tests/service_automation/tests/utilities/infra/api_util.py
> DOSIS-1819 Fix "default" WORKSPACE in service_automation

- services/data-migration/pipeline/cli.py
- services/data-migration/pipeline/processor.py
- services/data-migration/pipeline/transformer/base.py
- services/data-migration/pipeline/transformer/gp_practice.py
- services/data-migration/tests/unit/test_cli.py
- services/data-migration/tests/unit/test_processor.py
- services/data-migration/tests/unit/transformer/test_gp_practice.py
> FDOS-310 Allow for optional creation of entity types

- .github/workflows/quality-checks.yaml
- infrastructure/stacks/data_migration/lambda.tf
> FDOS-461 update sqs dependency

- .github/workflows/pipeline-deploy-application.yaml
- tests/service_automation/tests/conftest.py
- tests/service_automation/tests/step_definitions/common_steps/data_steps.py
- tests/service_automation/tests/step_definitions/common_steps/setup_steps.py
- tests/service_automation/tests/utilities/common/resource_name.py
- tests/service_automation/tests/utilities/infra/api_util.py
- tests/service_automation/tests/utilities/infra/dns_util.py
- tests/service_automation/tests/utilities/infra/repo_util.py
Fixed issue where test data might already exist due to edge cases in parallel pipeline stages
---
> DOSIS-1894 Checks for test data existence 

- infrastructure/common/locals.tf
- infrastructure/stacks/data_migration/data.tf
- infrastructure/stacks/data_migration/dms.tf
- infrastructure/stacks/data_migration/eventbridge.tf
- infrastructure/stacks/data_migration/lambda.tf
- infrastructure/stacks/data_migration/security_group.tf
> FDOS-524 Amend dms to deploy to int

- .github/workflows/pipeline-deploy-application.yaml
Trigger workflow when dependabot PR raised (not on creation of dependabot branch)
---
> FDOS-582 refactor dependabot trigger

- .github/workflows/deploy-architecture-pages.yaml
- .github/workflows/quality-checks.yaml
Because these PRs predate the change to automate the pipeline I have raised this to cover
- https://github.com/NHSDigital/ftrs-directory-of-services/pull/357
- https://github.com/NHSDigital/ftrs-directory-of-services/pull/341
---
> FDOS-000 Bump trivy and upload pages

- infrastructure/stacks/data_migration/dms.tf
- infrastructure/stacks/data_migration/iam.tf
- infrastructure/stacks/github_runner/app_github_runner_policy.json.tpl
> FDOS-524 fix dms bug

- docs/fhir/examples/Bundle-ServiceDetailsByOdsCode-Example.json
- docs/specification/dos-search.yaml
- docs/specification/ftrs-search.yaml
- services/gp-search/functions/ftrs_service/fhir_mapper/endpoint_mapper.py
- services/gp-search/tests/conftest.py
- services/gp-search/tests/unit/functions/ftrs_service/fhir_mapper/test_bundle_mapper.py
> DOSIS-1805 Update OAS after IOPS sign off

- .github/workflows/pipeline-deploy-application.yaml
> FDOS-572 Create diff concurrency group for deploy dms

- infrastructure/environments/int/account_wide.tfvars
- infrastructure/modules/s3/main.tf
- infrastructure/stacks/account_wide/s3.tf
- infrastructure/stacks/account_wide/variables.tf
- infrastructure/stacks/crud_apis/s3.tf
- infrastructure/stacks/etl_ods/s3.tf
- infrastructure/stacks/gp_search/s3.tf
- infrastructure/stacks/opensearch/s3.tf
- infrastructure/stacks/read_only_viewer/s3.tf
- infrastructure/stacks/terraform_management/s3.tf
> FDOS-417 add s3 access logging

- services/data-migration/pipeline/transformer/triage_code.py
- services/data-migration/tests/unit/transformer/test_triage_code.py
> FDOS-562 Set source for symptom discriminators

- infrastructure/common/versions.tf
- infrastructure/environments/int/crud_apis.tfvars
- infrastructure/environments/prod/crud_apis.tfvars
- infrastructure/local/versions.tf
- infrastructure/modules/lambda/main.tf
- infrastructure/modules/lambda/variables.tf
- infrastructure/modules/s3/main.tf
- infrastructure/remote/versions.tf
- infrastructure/stacks/crud_apis/lambda.tf
- infrastructure/stacks/crud_apis/variables.tf
- infrastructure/stacks/data_migration/data.tf
- infrastructure/stacks/data_migration/iam.tf
> FDOS-559 Add log retention for crud-api lambdas

- docs/specification/dos-search.yaml
- infrastructure/gp_search.tfvars
- infrastructure/stacks/gp_search/variables.tf
- services/gp-search/functions/gp_search_function.py
- services/gp-search/health_check/health_check_function.py
- services/gp-search/tests/manual_test.py
- services/gp-search/tests/unit/functions/test_gp_search_function.py
- services/gp-search/tests/unit/health_check/test_health_check_function.py
- tests/service_automation/tests/step_definitions/infra_steps/test_lambda.py
> DOSIS-2192 Proxy to Gateway fix

- infrastructure/stacks/account_policies/policies/rw_data.json
> FDOS-614 Add full quicksight perms to rw data

- infrastructure/stacks/data_migration/security_group.tf
Comment the rule causing the issue
---
> FDOS-601 Comment the rule causing the issue

- infrastructure/stacks/account_policies/policies/ro_compute.json
> FDOS-614 Permission to run athena lambdas

- infrastructure/stacks/data_migration/security_group.tf
Add the SG rule group back
---
> FDOS-601 Add the SG rule group back

- infrastructure/stacks/account_wide/waf.tf
> FDOS-599 Reordering WAF rules

- infrastructure/stacks/account_policies/policies/ro_data.json.tpl
> FDOS-614 Add access to folders

- infrastructure/stacks/account_wide/waf.tf
Add bot protection to waf web acl
---
> FDOS-587 Add bot protection to waf web acl

- infrastructure/stacks/opensearch/data.tf
- infrastructure/stacks/opensearch/opensearch_collection_policy.tf
- infrastructure/stacks/opensearch/opensearch_pipeline.tf
> FDOS-568 Opensearch single nap and dap
